# BEGIN DOTFILES SDDM OVERRIDE
[General]
DisplayServer=x11

[Theme]
ThemeDir=/usr/share/sddm/themes
Current=amadeus

[X11]
DisplayCommand=/usr/local/lib/sddm/Xsetup-dotfiles
# END DOTFILES SDDM OVERRIDE
