## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

// Screen size
screen.w = Window.GetWidth(0);
screen.h = Window.GetHeight(0);
screen.half.w = Window.GetWidth(0) / 2;
screen.half.h = Window.GetHeight(0) / 2;

// Question prompt
question = null;
answer = null;

// Message
message = null;

// Password prompt
bullets = null;
prompt = null;
bullet.image = Image.Text("*", 1, 1, 1);

// Flow
state.status = "play";
state.time = 0.0;

NUM_LOOP_FRAMES = 9;
NUM_END_FRAMES = 33;

//--------------------------------- Refresh (Logo animation) --------------------------

# cycle through all images
for (i = 0; i < NUM_LOOP_FRAMES; i++)
  loop_imgs[i] = Image("loop" + i + ".png");

for (i = 0; i < NUM_END_FRAMES; i++)
  end_imgs[i] = Image("end" + i + ".png");  

flyingman_sprite = Sprite();

# set image position
flyingman_sprite.SetX(Window.GetX() + (Window.GetWidth(0) / 2 - loop_imgs[0].GetWidth() / 2)); # Place images in the center
flyingman_sprite.SetY(Window.GetY() + (Window.GetHeight(0) / 2 - loop_imgs[0].GetHeight() / 2));

progress = 0;
curr_state = "loop";

fun refresh_callback ()
  {
    if (curr_state == "loop") {
      flyingman_sprite.SetImage(loop_imgs[Math.Int(progress / 2) % NUM_LOOP_FRAMES]);
      progress++;
    } else if (curr_state == "end") {
      if (progress < NUM_END_FRAMES) {
        flyingman_sprite.SetImage(end_imgs[progress]);
	progress++;
      } else {
        flyingman_sprite.SetImage(end_imgs[NUM_END_FRAMES - 1]);
      }
    }
  }

Plymouth.SetRefreshFunction (refresh_callback);

debug_sprite = Sprite();
debug_sprite.SetX(Window.GetX() + (Window.GetWidth(0) / 2 ));
debug_sprite.SetY(Window.GetY() + (Window.GetHeight(0) / 2 + 100));
fun progress_callback (duration, boot_progress)
  {
    debug_img = Image.Text(Math.Int(boot_progress * 100) + "%", 0.93, 0.713, 0.16, 1, "Monospace");
    debug_sprite.SetImage(debug_img);
    debug_sprite.SetX(Window.GetX() + (Window.GetWidth(0) / 2 - debug_img.GetWidth() / 2));
    if (boot_progress >= 0.90 && curr_state == "loop") {
      curr_state = "end";
      progress = 0;
    }
  }

Plymouth.SetBootProgressFunction(progress_callback);
//------------------------------------- Password prompt -------------------------------
fun DisplayQuestionCallback(prompt, entry) {
    question = null;
    answer = null;

    if (entry == "")
        entry = "<answer>";

    question.image = Image.Text(prompt, 1, 1, 1);
    question.sprite = Sprite(question.image);
    question.sprite.SetX(screen.half.w - question.image.GetWidth() / 2);
    question.sprite.SetY(screen.h - 4 * question.image.GetHeight());

    answer.image = Image.Text(entry, 1, 1, 1);
    answer.sprite = Sprite(answer.image);
    answer.sprite.SetX(screen.half.w - answer.image.GetWidth() / 2);
    answer.sprite.SetY(screen.h - 2 * answer.image.GetHeight());
}
Plymouth.SetDisplayQuestionFunction(DisplayQuestionCallback);

//------------------------------------- Password prompt -------------------------------
fun DisplayPasswordCallback(nil, bulletCount) {
    state.status = "pause";
    totalWidth = bulletCount * bullet.image.GetWidth();
    startPos = screen.half.w - totalWidth / 2;

    prompt.image = Image.Text("Enter Password", 1, 1, 1);
    prompt.sprite = Sprite(prompt.image);
    prompt.sprite.SetX(screen.half.w - prompt.image.GetWidth() / 2);
    prompt.sprite.SetY(screen.h - 4 * prompt.image.GetHeight());

    // Clear all bullets (user might hit backspace)
    bullets = null;
    for (i = 0; i < bulletCount; i++) {
        bullets[i].sprite = Sprite(bullet.image);
        bullets[i].sprite.SetX(startPos + i * bullet.image.GetWidth());
        bullets[i].sprite.SetY(screen.h - 2 * bullet.image.GetHeight());
    }
}
Plymouth.SetDisplayPasswordFunction(DisplayPasswordCallback);

//--------------------------- Normal display (unset all text) ----------------------
fun DisplayNormalCallback() {
    state.status = "play";
    bullets = null;
    prompt = null;
    message = null;
    question = null;
    answer = null;
}
Plymouth.SetDisplayNormalFunction(DisplayNormalCallback);

//----------------------------------------- Message --------------------------------
fun MessageCallback(text) {
    message.image = Image.Text(text, 1, 1, 1);
    message.sprite = Sprite(message.image);
    message.sprite.SetPosition(screen.half.w - message.image.GetWidth() / 2, message.image.GetHeight());
}
Plymouth.SetMessageFunction(MessageCallback);

